export const MoviesList = [
  {
    id: "tt0068646",
    url: "https://www.imdb.com/title/tt0068646/",
    primaryTitle: "The Godfather",
    originalTitle: "The Godfather",
    type: "movie",
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    primaryImage:
      "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_.jpg",
    trailer: "https://www.youtube.com/watch?v=8V2k2YQEQJ4",
    contentRating: "R",
    startYear: 1972,
    endYear: null,
    releaseDate: "1972-03-24",
    interests: ["Epic", "Gangster", "Tragedy", "Crime", "Drama"],
    countriesOfOrigin: ["US"],
    externalLinks: [
      "https://www.facebook.com/thegodfather/",
      "https://www.instagram.com/thegodfathermovie/",
    ],
    spokenLanguages: ["en", "it", "la"],
    filmingLocations: ["Forza d\u0027Agr\u00f2, Messina, Sicily, Italy"],
    productionCompanies: [
      {
        id: "co0023400",
        name: "Paramount Pictures",
      },
      {
        id: "co0921482",
        name: "Albert S. Ruddy Productions",
      },
      {
        id: "co0255097",
        name: "Alfran Productions",
      },
    ],
    budget: 6000000,
    grossWorldwide: 250342198,
    genres: ["Crime", "Drama"],
    isAdult: false,
    runtimeMinutes: 175,
    averageRating: 9.2,
    numVotes: 2112977,
    metascore: 100,
    directors: [
      {
        id: "nm0000338",
        url: "https://www.imdb.com/name/nm0000338/",
        fullName: "Francis Ford Coppola",
      },
    ],
    writers: [
      {
        id: "nm0000338",
        url: "https://www.imdb.com/name/nm0000338/",
        fullName: "Francis Ford Coppola",
      },
      {
        id: "nm0701374",
        url: "https://www.imdb.com/name/nm0701374/",
        fullName: "Mario Puzo",
      },
    ],
    cast: [
      {
        id: "nm0000008",
        url: "https://www.imdb.com/name/nm0000008/",
        fullName: "Marlon Brando",
        job: "actor",
        characters: ["Don Vito Corleone"],
      },
      {
        id: "nm0000199",
        url: "https://www.imdb.com/name/nm0000199/",
        fullName: "Al Pacino",
        job: "actor",
        characters: ["Michael"],
      },
      {
        id: "nm0001001",
        url: "https://www.imdb.com/name/nm0001001/",
        fullName: "James Caan",
        job: "actor",
        characters: ["Sonny Corleone", "Sonny"],
      },
      {
        id: "nm0000473",
        url: "https://www.imdb.com/name/nm0000473/",
        fullName: "Diane Keaton",
        job: "actress",
        characters: ["Kay Adams"],
      },
      {
        id: "nm0144710",
        url: "https://www.imdb.com/name/nm0144710/",
        fullName: "Richard S. Castellano",
        job: "actor",
        characters: ["Clemenza"],
      },
      {
        id: "nm0000380",
        url: "https://www.imdb.com/name/nm0000380/",
        fullName: "Robert Duvall",
        job: "actor",
        characters: ["Tom Hagen"],
      },
      {
        id: "nm0001330",
        url: "https://www.imdb.com/name/nm0001330/",
        fullName: "Sterling Hayden",
        job: "actor",
        characters: ["Capt. McCluskey"],
      },
      {
        id: "nm0549134",
        url: "https://www.imdb.com/name/nm0549134/",
        fullName: "John Marley",
        job: "actor",
        characters: ["Jack Woltz"],
      },
      {
        id: "nm0002017",
        url: "https://www.imdb.com/name/nm0002017/",
        fullName: "Richard Conte",
        job: "actor",
        characters: ["Barzini"],
      },
      {
        id: "nm0504803",
        url: "https://www.imdb.com/name/nm0504803/",
        fullName: "Al Lettieri",
        job: "actor",
        characters: ["Sollozzo"],
      },
      {
        id: "nm0000338",
        url: "https://www.imdb.com/name/nm0000338/",
        fullName: "Francis Ford Coppola",
        job: "director",
        characters: [],
      },
      {
        id: "nm0701374",
        url: "https://www.imdb.com/name/nm0701374/",
        fullName: "Mario Puzo",
        job: "writer",
        characters: [],
      },
      {
        id: "nm0000338",
        url: "https://www.imdb.com/name/nm0000338/",
        fullName: "Francis Ford Coppola",
        job: "writer",
        characters: [],
      },
      {
        id: "nm0748665",
        url: "https://www.imdb.com/name/nm0748665/",
        fullName: "Albert S. Ruddy",
        job: "producer",
        characters: [],
      },
      {
        id: "nm0000065",
        url: "https://www.imdb.com/name/nm0000065/",
        fullName: "Nino Rota",
        job: "composer",
        characters: [],
      },
      {
        id: "nm0932336",
        url: "https://www.imdb.com/name/nm0932336/",
        fullName: "Gordon Willis",
        job: "cinematographer",
        characters: [],
      },
      {
        id: "nm0722000",
        url: "https://www.imdb.com/name/nm0722000/",
        fullName: "William Reynolds",
        job: "editor",
        characters: [],
      },
      {
        id: "nm0957038",
        url: "https://www.imdb.com/name/nm0957038/",
        fullName: "Peter Zinner",
        job: "editor",
        characters: [],
      },
      {
        id: "nm0226544",
        url: "https://www.imdb.com/name/nm0226544/",
        fullName: "Louis DiGiaimo",
        job: "casting_director",
        characters: [],
      },
      {
        id: "nm0247622",
        url: "https://www.imdb.com/name/nm0247622/",
        fullName: "Andrea Eastman",
        job: "casting_director",
        characters: [],
      },
      {
        id: "nm0740407",
        url: "https://www.imdb.com/name/nm0740407/",
        fullName: "Fred Roos",
        job: "casting_director",
        characters: [],
      },
      {
        id: "nm0851790",
        url: "https://www.imdb.com/name/nm0851790/",
        fullName: "Dean Tavoularis",
        job: "production_designer",
        characters: [],
      },
    ],
  },
  {
    id: "tt15398776",
    url: "https://www.imdb.com/title/tt15398776/",
    primaryTitle: "Oppenheimer",
    originalTitle: "Oppenheimer",
    type: "movie",
    description:
      "A dramatization of the life story of J. Robert Oppenheimer, the physicist who had a large hand in the development of the atomic bombs that brought an end to World War II.",
    primaryImage:
      "https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZTJmNTM5MjVmYTQ4XkEyXkFqcGc@._V1_.jpg",
    trailer: null,
    contentRating: "R",
    startYear: 2023,
    endYear: null,
    releaseDate: "2023-07-21",
    interests: [
      "Docudrama",
      "Epic",
      "Historical Epic",
      "Period Drama",
      "Psychological Drama",
      "Biography",
      "Drama",
      "History",
    ],
    countriesOfOrigin: ["US", "GB"],
    externalLinks: [
      "https://www.facebook.com/OppenheimerMovie/",
      "https://www.instagram.com/oppenheimermovie/",
    ],
    spokenLanguages: ["en", "de", "it", "nl"],
    filmingLocations: ["Los Alamos, New Mexico, USA"],
    productionCompanies: [
      {
        id: "co0005073",
        name: "Universal Pictures",
      },
      {
        id: "co0028338",
        name: "Atlas Entertainment",
      },
      {
        id: "co1007122",
        name: "Gadget Films",
      },
    ],
    budget: 100000000,
    grossWorldwide: 975811333,
    genres: ["Biography", "Drama", "History"],
    isAdult: false,
    runtimeMinutes: 180,
    averageRating: 8.3,
    numVotes: 873793,
    metascore: 90,
    directors: [
      {
        id: "nm0634240",
        url: "https://www.imdb.com/name/nm0634240/",
        fullName: "Christopher Nolan",
      },
    ],
    writers: [
      {
        id: "nm0634240",
        url: "https://www.imdb.com/name/nm0634240/",
        fullName: "Christopher Nolan",
      },
      {
        id: "nm3284831",
        url: "https://www.imdb.com/name/nm3284831/",
        fullName: "Kai Bird",
      },
      {
        id: "nm2452558",
        url: "https://www.imdb.com/name/nm2452558/",
        fullName: "Martin Sherwin",
      },
    ],
    cast: [
      {
        id: "nm0614165",
        url: "https://www.imdb.com/name/nm0614165/",
        fullName: "Cillian Murphy",
        job: "actor",
        characters: ["J. Robert Oppenheimer"],
      },
      {
        id: "nm1289434",
        url: "https://www.imdb.com/name/nm1289434/",
        fullName: "Emily Blunt",
        job: "actress",
        characters: ["Kitty Oppenheimer"],
      },
      {
        id: "nm0000354",
        url: "https://www.imdb.com/name/nm0000354/",
        fullName: "Matt Damon",
        job: "actor",
        characters: ["Leslie Groves"],
      },
      {
        id: "nm0000375",
        url: "https://www.imdb.com/name/nm0000375/",
        fullName: "Robert Downey Jr.",
        job: "actor",
        characters: ["Lewis Strauss"],
      },
      {
        id: "nm2403277",
        url: "https://www.imdb.com/name/nm2403277/",
        fullName: "Alden Ehrenreich",
        job: "actor",
        characters: ["Senate Aide"],
      },
      {
        id: "nm0342241",
        url: "https://www.imdb.com/name/nm0342241/",
        fullName: "Scott Grimes",
        job: "actor",
        characters: ["Counsel"],
      },
      {
        id: "nm0164809",
        url: "https://www.imdb.com/name/nm0164809/",
        fullName: "Jason Clarke",
        job: "actor",
        characters: ["Roger Robb"],
      },
      {
        id: "nm0463282",
        url: "https://www.imdb.com/name/nm0463282/",
        fullName: "Kurt Koehler",
        job: "actor",
        characters: ["Thomas Morgan"],
      },
      {
        id: "nm0001282",
        url: "https://www.imdb.com/name/nm0001282/",
        fullName: "Tony Goldwyn",
        job: "actor",
        characters: ["Gordon Gray"],
      },
      {
        id: "nm0332944",
        url: "https://www.imdb.com/name/nm0332944/",
        fullName: "John Gowans",
        job: "actor",
        characters: ["Ward Evans"],
      },
      {
        id: "nm0634240",
        url: "https://www.imdb.com/name/nm0634240/",
        fullName: "Christopher Nolan",
        job: "director",
        characters: [],
      },
      {
        id: "nm0634240",
        url: "https://www.imdb.com/name/nm0634240/",
        fullName: "Christopher Nolan",
        job: "writer",
        characters: [],
      },
      {
        id: "nm3284831",
        url: "https://www.imdb.com/name/nm3284831/",
        fullName: "Kai Bird",
        job: "writer",
        characters: [],
      },
      {
        id: "nm2452558",
        url: "https://www.imdb.com/name/nm2452558/",
        fullName: "Martin Sherwin",
        job: "writer",
        characters: [],
      },
      {
        id: "nm0634240",
        url: "https://www.imdb.com/name/nm0634240/",
        fullName: "Christopher Nolan",
        job: "producer",
        characters: [],
      },
      {
        id: "nm0746273",
        url: "https://www.imdb.com/name/nm0746273/",
        fullName: "Charles Roven",
        job: "producer",
        characters: [],
      },
      {
        id: "nm0858799",
        url: "https://www.imdb.com/name/nm0858799/",
        fullName: "Emma Thomas",
        job: "producer",
        characters: [],
      },
      {
        id: "nm3234869",
        url: "https://www.imdb.com/name/nm3234869/",
        fullName: "Ludwig G\u00f6ransson",
        job: "composer",
        characters: [],
      },
      {
        id: "nm0887227",
        url: "https://www.imdb.com/name/nm0887227/",
        fullName: "Hoyte Van Hoytema",
        job: "cinematographer",
        characters: [],
      },
      {
        id: "nm2352780",
        url: "https://www.imdb.com/name/nm2352780/",
        fullName: "Jennifer Lame",
        job: "editor",
        characters: [],
      },
      {
        id: "nm0660667",
        url: "https://www.imdb.com/name/nm0660667/",
        fullName: "John Papsidera",
        job: "casting_director",
        characters: [],
      },
      {
        id: "nm1968338",
        url: "https://www.imdb.com/name/nm1968338/",
        fullName: "Ruth De Jong",
        job: "production_designer",
        characters: [],
      },
    ],
  },
  {
    id: "tt0172495",
    url: "https://www.imdb.com/title/tt0172495/",
    primaryTitle: "Gladiator",
    originalTitle: "Gladiator",
    type: "movie",
    description:
      "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    primaryImage:
      "https://m.media-amazon.com/images/M/MV5BYWQ4YmNjYjEtOWE1Zi00Y2U4LWI4NTAtMTU0MjkxNWQ1ZmJiXkEyXkFqcGc@._V1_.jpg",
    trailer: "https://www.youtube.com/watch?v=P5ieIbInFpg",
    contentRating: "R",
    startYear: 2000,
    endYear: null,
    releaseDate: "2000-05-05",
    interests: [
      "Action Epic",
      "Adventure Epic",
      "Epic",
      "Period Drama",
      "Sword \u0026 Sandal",
      "Action",
      "Adventure",
      "Drama",
    ],
    countriesOfOrigin: ["US", "GB", "MT", "MA"],
    externalLinks: ["https://www.facebook.com/GladiatorMovie/"],
    spokenLanguages: ["en"],
    filmingLocations: ["Ouarzazate, Morocco"],
    productionCompanies: [
      {
        id: "co0819670",
        name: "Dreamworks Pictures",
      },
      {
        id: "co0005073",
        name: "Universal Pictures",
      },
      {
        id: "co0074212",
        name: "Scott Free Productions",
      },
    ],
    budget: 103000000,
    grossWorldwide: 465516248,
    genres: ["Action", "Adventure", "Drama"],
    isAdult: false,
    runtimeMinutes: 155,
    averageRating: 8.5,
    numVotes: 1748750,
    metascore: 67,
    directors: [
      {
        id: "nm0000631",
        url: "https://www.imdb.com/name/nm0000631/",
        fullName: "Ridley Scott",
      },
    ],
    writers: [
      {
        id: "nm0291905",
        url: "https://www.imdb.com/name/nm0291905/",
        fullName: "David Franzoni",
      },
      {
        id: "nm0517589",
        url: "https://www.imdb.com/name/nm0517589/",
        fullName: "John Logan",
      },
      {
        id: "nm0629933",
        url: "https://www.imdb.com/name/nm0629933/",
        fullName: "William Nicholson",
      },
    ],
    cast: [
      {
        id: "nm0000128",
        url: "https://www.imdb.com/name/nm0000128/",
        fullName: "Russell Crowe",
        job: "actor",
        characters: ["Maximus"],
      },
      {
        id: "nm0001618",
        url: "https://www.imdb.com/name/nm0001618/",
        fullName: "Joaquin Phoenix",
        job: "actor",
        characters: ["Commodus"],
      },
      {
        id: "nm0001567",
        url: "https://www.imdb.com/name/nm0001567/",
        fullName: "Connie Nielsen",
        job: "actress",
        characters: ["Lucilla"],
      },
      {
        id: "nm0001657",
        url: "https://www.imdb.com/name/nm0001657/",
        fullName: "Oliver Reed",
        job: "actor",
        characters: ["Proximo"],
      },
      {
        id: "nm0001321",
        url: "https://www.imdb.com/name/nm0001321/",
        fullName: "Richard Harris",
        job: "actor",
        characters: ["Marcus Aurelius"],
      },
      {
        id: "nm0001394",
        url: "https://www.imdb.com/name/nm0001394/",
        fullName: "Derek Jacobi",
        job: "actor",
        characters: ["Gracchus"],
      },
      {
        id: "nm0005023",
        url: "https://www.imdb.com/name/nm0005023/",
        fullName: "Djimon Hounsou",
        job: "actor",
        characters: ["Juba"],
      },
      {
        id: "nm0774516",
        url: "https://www.imdb.com/name/nm0774516/",
        fullName: "David Schofield",
        job: "actor",
        characters: ["Falco"],
      },
      {
        id: "nm0795344",
        url: "https://www.imdb.com/name/nm0795344/",
        fullName: "John Shrapnel",
        job: "actor",
        characters: ["Gaius"],
      },
      {
        id: "nm0032962",
        url: "https://www.imdb.com/name/nm0032962/",
        fullName: "Tomas Arana",
        job: "actor",
        characters: ["Quintus"],
      },
      {
        id: "nm0000631",
        url: "https://www.imdb.com/name/nm0000631/",
        fullName: "Ridley Scott",
        job: "director",
        characters: [],
      },
      {
        id: "nm0291905",
        url: "https://www.imdb.com/name/nm0291905/",
        fullName: "David Franzoni",
        job: "writer",
        characters: [],
      },
      {
        id: "nm0517589",
        url: "https://www.imdb.com/name/nm0517589/",
        fullName: "John Logan",
        job: "writer",
        characters: [],
      },
      {
        id: "nm0629933",
        url: "https://www.imdb.com/name/nm0629933/",
        fullName: "William Nicholson",
        job: "writer",
        characters: [],
      },
      {
        id: "nm0291905",
        url: "https://www.imdb.com/name/nm0291905/",
        fullName: "David Franzoni",
        job: "producer",
        characters: [],
      },
      {
        id: "nm0527322",
        url: "https://www.imdb.com/name/nm0527322/",
        fullName: "Branko Lustig",
        job: "producer",
        characters: [],
      },
      {
        id: "nm0926824",
        url: "https://www.imdb.com/name/nm0926824/",
        fullName: "Douglas Wick",
        job: "producer",
        characters: [],
      },
      {
        id: "nm0314713",
        url: "https://www.imdb.com/name/nm0314713/",
        fullName: "Lisa Gerrard",
        job: "composer",
        characters: [],
      },
      {
        id: "nm0001877",
        url: "https://www.imdb.com/name/nm0001877/",
        fullName: "Hans Zimmer",
        job: "composer",
        characters: [],
      },
      {
        id: "nm0558822",
        url: "https://www.imdb.com/name/nm0558822/",
        fullName: "John Mathieson",
        job: "cinematographer",
        characters: [],
      },
      {
        id: "nm0768817",
        url: "https://www.imdb.com/name/nm0768817/",
        fullName: "Pietro Scalia",
        job: "editor",
        characters: [],
      },
      {
        id: "nm0226544",
        url: "https://www.imdb.com/name/nm0226544/",
        fullName: "Louis DiGiaimo",
        job: "casting_director",
        characters: [],
      },
      {
        id: "nm0561480",
        url: "https://www.imdb.com/name/nm0561480/",
        fullName: "Arthur Max",
        job: "production_designer",
        characters: [],
      },
    ],
  },
  {
    id: "tt0468569",
    url: "https://www.imdb.com/title/tt0468569/",
    primaryTitle: "The Dark Knight",
    originalTitle: "The Dark Knight",
    type: "movie",
    description:
      "When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.",
    primaryImage:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg",
    trailer: "https://www.youtube.com/watch?v=kmJLuwP3MbY",
    contentRating: "PG-13",
    startYear: 2008,
    endYear: null,
    releaseDate: "2008-07-18",
    interests: [
      "Action Epic",
      "Epic",
      "Superhero",
      "Tragedy",
      "Action",
      "Crime",
      "Drama",
      "Thriller",
    ],
    countriesOfOrigin: ["US", "GB"],
    externalLinks: [
      "https://www.facebook.com/darkknighttrilogy/",
      "https://www.warnerbros.co.uk/movies/dark-knight",
    ],
    spokenLanguages: ["en"],
    filmingLocations: ["Chicago, Illinois, USA"],
    productionCompanies: [
      {
        id: "co0002663",
        name: "Warner Bros.",
      },
      {
        id: "co0159111",
        name: "Legendary Entertainment",
      },
      {
        id: "co0147954",
        name: "Syncopy",
      },
    ],
    budget: 185000000,
    grossWorldwide: 1009057329,
    genres: ["Action", "Crime", "Drama"],
    isAdult: false,
    runtimeMinutes: 152,
    averageRating: 9,
    numVotes: 3003886,
    metascore: 84,
    directors: [
      {
        id: "nm0634240",
        url: "https://www.imdb.com/name/nm0634240/",
        fullName: "Christopher Nolan",
      },
    ],
    writers: [
      {
        id: "nm0634240",
        url: "https://www.imdb.com/name/nm0634240/",
        fullName: "Christopher Nolan",
      },
      {
        id: "nm0634300",
        url: "https://www.imdb.com/name/nm0634300/",
        fullName: "Jonathan Nolan",
      },
      {
        id: "nm0275286",
        url: "https://www.imdb.com/name/nm0275286/",
        fullName: "David S. Goyer",
      },
      {
        id: "nm0004170",
        url: "https://www.imdb.com/name/nm0004170/",
        fullName: "Bob Kane",
      },
    ],
    cast: [
      {
        id: "nm0000288",
        url: "https://www.imdb.com/name/nm0000288/",
        fullName: "Christian Bale",
        job: "actor",
        characters: ["Bruce Wayne", "Batman"],
      },
      {
        id: "nm0005132",
        url: "https://www.imdb.com/name/nm0005132/",
        fullName: "Heath Ledger",
        job: "actor",
        characters: ["Joker"],
      },
      {
        id: "nm0001173",
        url: "https://www.imdb.com/name/nm0001173/",
        fullName: "Aaron Eckhart",
        job: "actor",
        characters: ["Harvey Dent"],
      },
      {
        id: "nm0000323",
        url: "https://www.imdb.com/name/nm0000323/",
        fullName: "Michael Caine",
        job: "actor",
        characters: ["Alfred"],
      },
      {
        id: "nm0350454",
        url: "https://www.imdb.com/name/nm0350454/",
        fullName: "Maggie Gyllenhaal",
        job: "actress",
        characters: ["Rachel"],
      },
      {
        id: "nm0000198",
        url: "https://www.imdb.com/name/nm0000198/",
        fullName: "Gary Oldman",
        job: "actor",
        characters: ["Gordon"],
      },
      {
        id: "nm0000151",
        url: "https://www.imdb.com/name/nm0000151/",
        fullName: "Morgan Freeman",
        job: "actor",
        characters: ["Lucius Fox"],
      },
      {
        id: "nm1010931",
        url: "https://www.imdb.com/name/nm1010931/",
        fullName: "Monique Gabriela Curnen",
        job: "actress",
        characters: ["Ramirez"],
      },
      {
        id: "nm0212939",
        url: "https://www.imdb.com/name/nm0212939/",
        fullName: "Ron Dean",
        job: "actor",
        characters: ["Wuertz"],
      },
      {
        id: "nm0614165",
        url: "https://www.imdb.com/name/nm0614165/",
        fullName: "Cillian Murphy",
        job: "actor",
        characters: ["Scarecrow"],
      },
      {
        id: "nm0634240",
        url: "https://www.imdb.com/name/nm0634240/",
        fullName: "Christopher Nolan",
        job: "director",
        characters: [],
      },
      {
        id: "nm0634300",
        url: "https://www.imdb.com/name/nm0634300/",
        fullName: "Jonathan Nolan",
        job: "writer",
        characters: [],
      },
      {
        id: "nm0634240",
        url: "https://www.imdb.com/name/nm0634240/",
        fullName: "Christopher Nolan",
        job: "writer",
        characters: [],
      },
      {
        id: "nm0275286",
        url: "https://www.imdb.com/name/nm0275286/",
        fullName: "David S. Goyer",
        job: "writer",
        characters: [],
      },
      {
        id: "nm0004170",
        url: "https://www.imdb.com/name/nm0004170/",
        fullName: "Bob Kane",
        job: "writer",
        characters: [],
      },
      {
        id: "nm0634240",
        url: "https://www.imdb.com/name/nm0634240/",
        fullName: "Christopher Nolan",
        job: "producer",
        characters: [],
      },
      {
        id: "nm0650038",
        url: "https://www.imdb.com/name/nm0650038/",
        fullName: "Lorne Orleans",
        job: "producer",
        characters: [],
      },
      {
        id: "nm0746273",
        url: "https://www.imdb.com/name/nm0746273/",
        fullName: "Charles Roven",
        job: "producer",
        characters: [],
      },
      {
        id: "nm0858799",
        url: "https://www.imdb.com/name/nm0858799/",
        fullName: "Emma Thomas",
        job: "producer",
        characters: [],
      },
      {
        id: "nm0006133",
        url: "https://www.imdb.com/name/nm0006133/",
        fullName: "James Newton Howard",
        job: "composer",
        characters: [],
      },
      {
        id: "nm0001877",
        url: "https://www.imdb.com/name/nm0001877/",
        fullName: "Hans Zimmer",
        job: "composer",
        characters: [],
      },
      {
        id: "nm0002892",
        url: "https://www.imdb.com/name/nm0002892/",
        fullName: "Wally Pfister",
        job: "cinematographer",
        characters: [],
      },
      {
        id: "nm0809059",
        url: "https://www.imdb.com/name/nm0809059/",
        fullName: "Lee Smith",
        job: "editor",
        characters: [],
      },
      {
        id: "nm0660667",
        url: "https://www.imdb.com/name/nm0660667/",
        fullName: "John Papsidera",
        job: "casting_director",
        characters: [],
      },
      {
        id: "nm0189769",
        url: "https://www.imdb.com/name/nm0189769/",
        fullName: "Nathan Crowley",
        job: "production_designer",
        characters: [],
      },
    ],
  },
];
